//Get Student Action Type
export const GET_STUDENT_PENDING = "GET_STUDENT_PENDING";
export const GET_STUDENT_FULLFILL = "GET_STUDENT_FULLFILL";
export const GET_STUDENT_REJECTED = "GET_STUDENT_REJECTED";

//Create Student Action Type
export const CREATE_STUDENT_PENDING = "CREATE_STUDENT_PENDING";
export const CREATE_STUDENT_FULLFILL = "CREATE_STUDENT_FULLFILL";
export const CREATE_STUDENT_REJECTED = "CREATE_STUDENT_REJECTED";

//Delete Student Action Type
export const DELETE_STUDENT_PENDING = "DELETE_STUDENT_PENDING";
export const DELETE_STUDENT_FULLFILL = "DELETE_STUDENT_FULLFILL";
export const DELETE_STUDENT_REJECTED = "DELETE_STUDENT_REJECTED";

//Edit Student Action Type
export const EDIT_STUDENT_PENDING = "EDIT_STUDENT_PENDING";
export const EDIT_STUDENT_FULLFILL = "EDIT_STUDENT_FULLFILL";
export const EDIT_STUDENT_REJECTED = "EDIT_STUDENT_REJECTED";

//Edit Student Value Action Type
export const EDIT_STUDENT_DATA = "EDIT_STUDENT_DATA";
